// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/flake-idgen/flake-idgen.d.ts
declare module 'flake-idgen' {
	interface ConstructorOptions {
		datacenter?: number;
		worker?: number;
		id?: number;
		epoch?: number;
		seqMask?: number;
	}

	class FlakeId {
		constructor(options?: ConstructorOptions);
		next(callback?: (err: Error, id: any) => void): any;
	}
	export = FlakeId;
}